spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_management
    username: projectuser
    password: projectuser
  data:
    rest:
      base-path: /api
  jpa:
    show-sql: true
server:
  error:
    include-stacktrace: never
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#  level:
#    root: debug
#    org.springframework: debug